export default interface OrganizationModel {
  organizationId: string;
  organizationName: string;
  address1: string;
  address2: string;
  city: string;
  state: string;
  zipCode: string;
  phone: string;
  fax: string;
  emailAddress: string;
  permitNumber: string;
  contactName: string;
  preferredUnitsType: string;
  hatchlingBalanceAsOfDate: Date;
  ccHatchlingStartingBalance: number;
  cmHatchlingStartingBalance: number;
  dcHatchlingStartingBalance: number;
  otherHatchlingStartingBalance: number;
  unknownHatchlingStartingBalance: number;
  washbackBalanceAsOfDate: Date;
  ccWashbackStartingBalance: number;
  cmWashbackStartingBalance: number;
  dcWashbackStartingBalance: number;
  otherWashbackStartingBalance: number;
  unknownWashbackStartingBalance: number;
};
